Add workaround for glibc compile problem
Link error: undefined reference to `fstatat64'
Appears due to the combination of "-Os" compiler option and inlining
some system calls.
http://sourceware.org/bugzilla/show_bug.cgi?id=5203

Patch is not applied by default, modify the bb recipe if you need it